apiVersion: v1
kind: Service
metadata:
  name: dobby-nodeport-service
spec:
  type: NodePort
  selector:
    app: dobby-nodeport
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 30006