apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dobby-rs
  labels:
    app: dobby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dobby-cluster
  template:
    metadata:
      labels:
        app: dobby-cluster
    spec:
      containers:
        - name: dobby-cluster
          image: thecasualcoder/dobby
          ports:
            - containerPort: 4444