apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      containers:
        - name: test-container
          image: curlimages/curl
          command: ["/bin/sh", "-c", "echo 'I am doing my job'; ls -al; sleep 5"]
      restartPolicy: OnFailure
  backoffLimit: 4