apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "sleep 5000" ]
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/config
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret